services:
  mysql:
    image: mysql:latest
    restart: always
    container_name: mysql
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - ./mysql/db/00_init.sql:/docker-entrypoint-initdb.d/00_init.sql
      - ./mysql/csv_data:/var/lib/mysql-files
    environment:
      MYSQL_DATABASE: 'hr_management'
      MYSQL_ROOT_PASSWORD: 'adminadmin'
      MYSQL_PASSWORD: 'adminadmin'

  api:
    depends_on:
      - mysql
    container_name: rest-api-docker
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: unless-stopped
    links:
      - mysql
    volumes:
      - ./api:/app
    ports:
      - "5000:5000"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: hr_management
      DB_USER: root
      DB_PASSWORD: adminadmin