version: "3"
services:
  mysql:
    image: mysql:latest
    restart: always
    container_name: mysql
    platform: linux/x86_64
    ports:
      - '3306:3306'
    volumes:
      - ./mysql/db/00_jobs_table.sql:/docker-entrypoint-initdb.d/00_jobs_table.sql
      - ./mysql/db/01_departments_table.sql:/docker-entrypoint-initdb.d/01_departments_table.sql
      - ./mysql/db/02_hired_employees.sql:/docker-entrypoint-initdb.d/02_hired_employees.sql
    environment:
      - MYSQL_ROOT_PASSWORD=adminadmin
      - MYSQL_DATABASE=hr_management
    env_file:
      - ./mysql/local.env

  api:
    depends_on:
      - mysql
    container_name: rest-api-docker
    platform: linux/x86_64
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./api:/app
    ports:
      - 8000:8000
    env_file:
      - ./api/local.env